### ISSUE TITLE
Contributing for support of Dynamixel protocol v2.0

### ISSUE THREAD

**Issue by cheng-chi** [jacquev6/Pynamixel#2]
Hi @jacquev6, I'm an undergraduate student at the University of Michigan. During our final project of a robotic course, we found Pynamixel library to be very helpful and intuitive for controlling dynamical servos. However, the current version of pynamixel does not support XL 320 servo, which uses [protocol v2.0](http://emanual.robotis.com/docs/en/dxl/protocol2/). We [forked](https://gitlab.eecs.umich.edu/eecs467-cinebot/Pynamixel) this repository and added support for protocol v2.0 read and write instructions. We would like to contribute our work back to this project and potentially have an update on the official pip. Should I just submit a pull request?

**Comment by jacquev6** [comment]
That sounds great! I'm very glad *Pynamixel* helped you, and that you want to contribute back!

So, to answer your question, **yes, please open a PR** on GitHub. Your current fork is on your university's GitLab, which I can't access. You'll have to fork Pynamixel on GitHub and push your work here. I'm looking forward to reading your code!

If at all possible, I'd also love to know more about your project. What is it about? What hardware did you use to communicate with the Dynamixel bus? etc.

**Comment by cheng-chi** [comment]
@jacquev6 Thanks for your fast response! I have just uploaded our [fork ](https://github.com/cheng-chi/Pynamixel) onto GitHub. I will be working on a PR soon after the final project deadline of our course (next week).

Our project is about making a small 6 DoF robot arm with a camera on the end-effector, similar to the one being used in movie _Gravity_ or [MVMC Bolt](https://www.mrmoco.com/thebolt/). We decided to use a Dynamixel XL-320 servo on the top-most axis to reduce flying weight, but XL-320 only supports protocol v2. Some of the results have been posted in this [playlist](https://www.youtube.com/playlist?list=PLlRSMfYLz8lIm3YkHxYW8T8PUMn3j_UAa). 
![IMG_3495](https://user-images.githubusercontent.com/24358464/56401891-165ebf00-6229-11e9-94af-81c6e9ea5cf7.JPG)

**Comment by jacquev6** [comment]
Awesome project, reminds me of my studies! The rice video looks great!

I've had a quick look at your code and I find it globally good. I'm a bit uncomfortable with the maintainability of the many `if`s checking for protocol v1 vs v2. I'll think about other designs for that point, but I'll merge and publish your contribution as-is.

There is a small blocking point though: your repo is *not* a GitHub fork of mine. (You created a new unrelated repo and pushed your code to it). That means you won't be able to submit a PR from it. You should delete your GitHub repo, then fork mine using the `fork` button, to let GitHub know how our works relate.

Don't rush anything for me. Focus on your deadline, and I'll have a deeper look at your PR when you can open it.

**Comment by jacquev6** [comment]
Hi there @cheng-chi, did you project deadline go well? Do you know when you will follow-up on this PR? It's often difficult to find time for projects after they're done, but I would really like to include your contribution.

**Comment by cheng-chi** [comment]
Hi @jacquev6 , sorry about the delay! I just finished the final project for another course (a stressful semester). By the time I created my repo, I didn't think about being able to merge this repo back to original. Thus, I modified the license file and some copyright notice according to some tutorial online. However, I'm perfectly fine about changing those back! Also, this is my first ever pull request, so please let me know if I messed anything up.

**Comment by jacquev6** [comment]
No worries, thank you for your contribution!

I'm closing this issue now, let's discuss in #3.
